//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SISTEMEMPRESA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AUDCNTBDETC
    {
        public int IdAudCntbDetC { get; set; }
        public Nullable<int> IdCntbRegDetalleCont { get; set; }
        public string UsuarioIngreso { get; set; }
        public Nullable<System.DateTime> FechaIngreso { get; set; }
        public string AudUsuarioModificacion { get; set; }
        public Nullable<System.DateTime> AudFechaModificacion { get; set; }
        public string AudNombreServidor { get; set; }
        public Nullable<System.DateTime> AudFecha { get; set; }
        public string AudAccion { get; set; }
    
        public virtual CNTBREGDETALLECONT CNTBREGDETALLECONT { get; set; }
    }
}
