//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SISTEMEMPRESA.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class CNTBREGCABECERACONT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CNTBREGCABECERACONT()
        {
            this.AUDCNTBCABC = new HashSet<AUDCNTBCABC>();
            this.CNTBREGDETALLECONT = new HashSet<CNTBREGDETALLECONT>();
        }
    
        [Required]
        [Display(Name ="Numero Cabecera")]
        public int IdCntbRegCabeceraCont { get; set; }
        [Required]
        [Display(Name = "Periodo")]
        public short periodo { get; set; }
        [Required]
        [Display(Name = "Nombre Lote")]
        public string NombreLote { get; set; }
        [Display(Name = "Total Debe")]
        public Nullable<decimal> TotalDebe { get; set; }
        [Display(Name = "Total Haber")]
        public Nullable<decimal> TotalHaber { get; set; }
        [Required]
        [Display(Name = "Estado Contable")]
        public string EstadoContable { get; set; }
        [Display(Name = "Observacion")]
        public string observacion { get; set; }
        [Required]
        [Display(Name = "Estado")]
        public string estado { get; set; }
        [Required]
        [Display(Name = "Usuario")]
        public string UsuarioSistema { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AUDCNTBCABC> AUDCNTBCABC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CNTBREGDETALLECONT> CNTBREGDETALLECONT { get; set; }
    }
}
