//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SISTEMEMPRESA.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class CNTBPLANDECUENTA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CNTBPLANDECUENTA()
        {
            this.CNTBREGDETALLECONT = new HashSet<CNTBREGDETALLECONT>();
        }
        
        [Required]
        [Display(Name ="Codigo Cuenta")]
        public int IdCntbPlanDeCuenta { get; set; }
        [Required]
        [Display(Name = "Periodo")]
        public short periodo { get; set; }
        [Required]
        [Display(Name = "Detalle")]
        public string detalle { get; set; }
        [Required]
        [Display(Name = "Naturaleza")]
        public string naturaleza { get; set; }
        [Required]
        [Display(Name = "Estado")]
        public string estado { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CNTBREGDETALLECONT> CNTBREGDETALLECONT { get; set; }
    }
}
