//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SISTEMEMPRESA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CNTBSALDOCONTABLE
    {
        public int IdCntbSaldoContable { get; set; }
        public Nullable<int> IdCntbRegDetalleCont { get; set; }
        public short periodo { get; set; }
        public int NumeroLote { get; set; }
        public int CuentaContable { get; set; }
        public Nullable<decimal> SaldoContableDebe { get; set; }
        public Nullable<decimal> SaldoContableHaber { get; set; }
        public string estado { get; set; }
    
        public virtual CNTBREGDETALLECONT CNTBREGDETALLECONT { get; set; }
    }
}
