//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SISTEMEMPRESA.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class CNTBREGDETALLECONT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CNTBREGDETALLECONT()
        {
            this.AUDCNTBDETC = new HashSet<AUDCNTBDETC>();
            this.CNTBSALDOCONTABLE = new HashSet<CNTBSALDOCONTABLE>();
        }
    
        public int IdCntbRegDetalleCont { get; set; }
        [Required]
        [Display(Name = "Periodo")]
        public short periodo { get; set; }
        [Required]
        [Display(Name = "Numero Cabecera")]
        public Nullable<int> IdCntbRegCabeceraCont { get; set; }
        [Required]
        [Display(Name = "Secuencia Registros")]
        public int SecuenciaDetalle { get; set; }
        [Required]
        [Display(Name = "Codigo Cuenta")]
        public Nullable<int> IdCntbPlanDeCuenta { get; set; }
        [Required]
        [Display(Name = "Glosa Contable")]
        public string GlosaContable { get; set; }
        [Required]
        [Display(Name = "Fecha Contable")]
        public System.DateTime FechaContable { get; set; }
        [Required]
        [Display(Name = "Afectacion")]
        public string afectacion { get; set; }
        [Required]
        [Display(Name = "Monto")]
        public decimal monto { get; set; }
        [Required]
        [Display(Name = "Estado")]
        public string estado { get; set; }
        [Required]
        [Display(Name = "Usuario")]
        public string UsuarioSistema { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AUDCNTBDETC> AUDCNTBDETC { get; set; }
        public virtual CNTBPLANDECUENTA CNTBPLANDECUENTA { get; set; }
        public virtual CNTBREGCABECERACONT CNTBREGCABECERACONT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CNTBSALDOCONTABLE> CNTBSALDOCONTABLE { get; set; }
    }
}
