//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SISTEMEMPRESA.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ConnDbSISTEMAEMPRESA : DbContext
    {
        public ConnDbSISTEMAEMPRESA()
            : base("name=ConnDbSISTEMAEMPRESA")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<SEGDEPARTAMENTO> SEGDEPARTAMENTO { get; set; }
        public virtual DbSet<SEGMODULO> SEGMODULO { get; set; }
        public virtual DbSet<SEGOPERACION> SEGOPERACION { get; set; }
        public virtual DbSet<SEGROL> SEGROL { get; set; }
        public virtual DbSet<SEGROLOPERACION> SEGROLOPERACION { get; set; }
        public virtual DbSet<SEGUSUARIOSISTEMA> SEGUSUARIOSISTEMA { get; set; }
        public virtual DbSet<AUDCNTBCABC> AUDCNTBCABC { get; set; }
        public virtual DbSet<AUDCNTBDETC> AUDCNTBDETC { get; set; }
        public virtual DbSet<CNTBPLANDECUENTA> CNTBPLANDECUENTA { get; set; }
        public virtual DbSet<CNTBREGCABECERACONT> CNTBREGCABECERACONT { get; set; }
        public virtual DbSet<CNTBREGDETALLECONT> CNTBREGDETALLECONT { get; set; }
        public virtual DbSet<CNTBSALDOCONTABLE> CNTBSALDOCONTABLE { get; set; }
    }
}
