//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SISTEMEMPRESA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEGDEPARTAMENTO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SEGDEPARTAMENTO()
        {
            this.SEGUSUARIOSISTEMA = new HashSet<SEGUSUARIOSISTEMA>();
        }
    
        public int IdSegDepartamento { get; set; }
        public string nombre { get; set; }
        public string estado { get; set; }
        public string UsuarioIngreso { get; set; }
        public System.DateTime FechaIngreso { get; set; }
        public string UsuarioModificacion { get; set; }
        public System.DateTime FechaModificacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SEGUSUARIOSISTEMA> SEGUSUARIOSISTEMA { get; set; }
    }
}
