//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SISTEMEMPRESA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEGUSUARIOSISTEMA
    {
        public int IdSegUsuarioSistema { get; set; }
        public Nullable<int> IdSegDepartamento { get; set; }
        public Nullable<int> IdSegRol { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
        public string UsuarioSistema { get; set; }
        public string clave { get; set; }
        public string UsuarioIngreso { get; set; }
        public System.DateTime FechaIngreso { get; set; }
        public string UsuarioModificacion { get; set; }
        public System.DateTime FechaModificacion { get; set; }
    
        public virtual SEGDEPARTAMENTO SEGDEPARTAMENTO { get; set; }
        public virtual SEGROL SEGROL { get; set; }
    }
}
